name: CICD

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: Login to dockerr hub
        uses: docker  login -u ${{ secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run:  docker build -t vikas033/server .
      - name: Publish image to docker hub
        run:  docker push vikas033/sever:latest

   deploy:    
      needs: build
      runs-on: [aws-ec2]
      steps:
         - name: Pull image from docker hub
           run: docker pull vikas033/server:latest
         - name: Delete old container
           run: docker rm -f server-container
         - name: Run docker container
           run: docker run -d -p 5000:5000 -name server-container vikas033/server